import { createContext, useEffect, useState } from "react";
import PropTypes from "prop-types";
export const AppContext = createContext();

export const AppProvider = ({ children }) => {
  const [windowWidth, setWindowWidth] = useState(window.innerWidth);
  const [activeLetters, setActiveLetters] = useState([
    { letter: "q", active: true },
    { letter: "w", active: true },
    { letter: "e", active: true },
    { letter: "r", active: true },
    { letter: "t", active: true },
    { letter: "y", active: true },
    { letter: "u", active: true },
    { letter: "i", active: true },
    { letter: "o", active: true },
    { letter: "p", active: true },
    { letter: "a", active: true },
    { letter: "s", active: true },
    { letter: "d", active: true },
    { letter: "f", active: true },
    { letter: "g", active: true },
    { letter: "h", active: true },
    { letter: "j", active: true },
    { letter: "k", active: true },
    { letter: "l", active: true },
    { letter: "z", active: true },
    { letter: "x", active: true },
    { letter: "c", active: true },
    { letter: "v", active: true },
    { letter: "b", active: true },
    { letter: "n", active: true },
    { letter: "m", active: true },
  ]);
  const [particularActiveLetters, setParticularActiveLetters] = useState([
    [
      { letter: "q", active: activeLetters[0].active },
      { letter: "w", active: activeLetters[1].active },
      { letter: "e", active: activeLetters[2].active },
      { letter: "r", active: activeLetters[3].active },
      { letter: "t", active: activeLetters[4].active },
      { letter: "y", active: activeLetters[5].active },
      { letter: "u", active: activeLetters[6].active },
      { letter: "i", active: activeLetters[7].active },
      { letter: "o", active: activeLetters[8].active },
      { letter: "p", active: activeLetters[9].active },
      { letter: "a", active: activeLetters[10].active },
      { letter: "s", active: activeLetters[11].active },
      { letter: "d", active: activeLetters[12].active },
      { letter: "f", active: activeLetters[13].active },
      { letter: "g", active: activeLetters[14].active },
      { letter: "h", active: activeLetters[15].active },
      { letter: "j", active: activeLetters[16].active },
      { letter: "k", active: activeLetters[17].active },
      { letter: "l", active: activeLetters[18].active },
      { letter: "z", active: activeLetters[19].active },
      { letter: "x", active: activeLetters[20].active },
      { letter: "c", active: activeLetters[21].active },
      { letter: "v", active: activeLetters[22].active },
      { letter: "b", active: activeLetters[23].active },
      { letter: "n", active: activeLetters[24].active },
      { letter: "m", active: activeLetters[25].active },
    ],
    [
      { letter: "q", active: activeLetters[0].active },
      { letter: "w", active: activeLetters[1].active },
      { letter: "e", active: activeLetters[2].active },
      { letter: "r", active: activeLetters[3].active },
      { letter: "t", active: activeLetters[4].active },
      { letter: "y", active: activeLetters[5].active },
      { letter: "u", active: activeLetters[6].active },
      { letter: "i", active: activeLetters[7].active },
      { letter: "o", active: activeLetters[8].active },
      { letter: "p", active: activeLetters[9].active },
      { letter: "a", active: activeLetters[10].active },
      { letter: "s", active: activeLetters[11].active },
      { letter: "d", active: activeLetters[12].active },
      { letter: "f", active: activeLetters[13].active },
      { letter: "g", active: activeLetters[14].active },
      { letter: "h", active: activeLetters[15].active },
      { letter: "j", active: activeLetters[16].active },
      { letter: "k", active: activeLetters[17].active },
      { letter: "l", active: activeLetters[18].active },
      { letter: "z", active: activeLetters[19].active },
      { letter: "x", active: activeLetters[20].active },
      { letter: "c", active: activeLetters[21].active },
      { letter: "v", active: activeLetters[22].active },
      { letter: "b", active: activeLetters[23].active },
      { letter: "n", active: activeLetters[24].active },
      { letter: "m", active: activeLetters[25].active },
    ],
    [
      { letter: "q", active: activeLetters[0].active },
      { letter: "w", active: activeLetters[1].active },
      { letter: "e", active: activeLetters[2].active },
      { letter: "r", active: activeLetters[3].active },
      { letter: "t", active: activeLetters[4].active },
      { letter: "y", active: activeLetters[5].active },
      { letter: "u", active: activeLetters[6].active },
      { letter: "i", active: activeLetters[7].active },
      { letter: "o", active: activeLetters[8].active },
      { letter: "p", active: activeLetters[9].active },
      { letter: "a", active: activeLetters[10].active },
      { letter: "s", active: activeLetters[11].active },
      { letter: "d", active: activeLetters[12].active },
      { letter: "f", active: activeLetters[13].active },
      { letter: "g", active: activeLetters[14].active },
      { letter: "h", active: activeLetters[15].active },
      { letter: "j", active: activeLetters[16].active },
      { letter: "k", active: activeLetters[17].active },
      { letter: "l", active: activeLetters[18].active },
      { letter: "z", active: activeLetters[19].active },
      { letter: "x", active: activeLetters[20].active },
      { letter: "c", active: activeLetters[21].active },
      { letter: "v", active: activeLetters[22].active },
      { letter: "b", active: activeLetters[23].active },
      { letter: "n", active: activeLetters[24].active },
      { letter: "m", active: activeLetters[25].active },
    ],
    [
      { letter: "q", active: activeLetters[0].active },
      { letter: "w", active: activeLetters[1].active },
      { letter: "e", active: activeLetters[2].active },
      { letter: "r", active: activeLetters[3].active },
      { letter: "t", active: activeLetters[4].active },
      { letter: "y", active: activeLetters[5].active },
      { letter: "u", active: activeLetters[6].active },
      { letter: "i", active: activeLetters[7].active },
      { letter: "o", active: activeLetters[8].active },
      { letter: "p", active: activeLetters[9].active },
      { letter: "a", active: activeLetters[10].active },
      { letter: "s", active: activeLetters[11].active },
      { letter: "d", active: activeLetters[12].active },
      { letter: "f", active: activeLetters[13].active },
      { letter: "g", active: activeLetters[14].active },
      { letter: "h", active: activeLetters[15].active },
      { letter: "j", active: activeLetters[16].active },
      { letter: "k", active: activeLetters[17].active },
      { letter: "l", active: activeLetters[18].active },
      { letter: "z", active: activeLetters[19].active },
      { letter: "x", active: activeLetters[20].active },
      { letter: "c", active: activeLetters[21].active },
      { letter: "v", active: activeLetters[22].active },
      { letter: "b", active: activeLetters[23].active },
      { letter: "n", active: activeLetters[24].active },
      { letter: "m", active: activeLetters[25].active },
    ],
    [
      { letter: "q", active: activeLetters[0].active },
      { letter: "w", active: activeLetters[1].active },
      { letter: "e", active: activeLetters[2].active },
      { letter: "r", active: activeLetters[3].active },
      { letter: "t", active: activeLetters[4].active },
      { letter: "y", active: activeLetters[5].active },
      { letter: "u", active: activeLetters[6].active },
      { letter: "i", active: activeLetters[7].active },
      { letter: "o", active: activeLetters[8].active },
      { letter: "p", active: activeLetters[9].active },
      { letter: "a", active: activeLetters[10].active },
      { letter: "s", active: activeLetters[11].active },
      { letter: "d", active: activeLetters[12].active },
      { letter: "f", active: activeLetters[13].active },
      { letter: "g", active: activeLetters[14].active },
      { letter: "h", active: activeLetters[15].active },
      { letter: "j", active: activeLetters[16].active },
      { letter: "k", active: activeLetters[17].active },
      { letter: "l", active: activeLetters[18].active },
      { letter: "z", active: activeLetters[19].active },
      { letter: "x", active: activeLetters[20].active },
      { letter: "c", active: activeLetters[21].active },
      { letter: "v", active: activeLetters[22].active },
      { letter: "b", active: activeLetters[23].active },
      { letter: "n", active: activeLetters[24].active },
      { letter: "m", active: activeLetters[25].active },
    ],
  ]);
  const [word, setWord] = useState(["", "", "", "", ""]);

  const providerValue = {
    windowWidth,
    activeLetters,
    setActiveLetters,
    word,
    setWord,
    particularActiveLetters,
    setParticularActiveLetters,
  };

  useEffect(() => {
    const handleResize = () => {
      setWindowWidth(window.innerWidth);
    };

    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <AppContext.Provider value={providerValue}>{children}</AppContext.Provider>
  );
};

AppProvider.propTypes = {
  children: PropTypes.node.isRequired,
};

export default AppProvider;
